mod handle_error;

fn main() {
    handle_error::handle_errors_correctly_in_main();
}
